type: web
name: vehicle-service-system

services:
  # API Gateway
  - name: api-gateway
    git:
      repository: github.com/jeetmundra52-web/vehicle-service-system
      branch: main
      workdir: microservices/api-gateway
    build:
      command: npm install
    run:
      command: node index.js
    env:
      PORT: 8000
    routes:
      - path: /api
        port: 8000

  # Auth Service
  - name: auth-service
    git:
      repository: github.com/jeetmundra52-web/vehicle-service-system
      branch: main
      workdir: microservices/auth-service
    build:
      command: npm install
    run:
      command: node index.js
    env:
      PORT: 8000
      # MONGO_URI needs to be added in Koyeb Dashboard
    ports:
      - port: 8000
        protocol: http

  # Booking Service
  - name: booking-service
    git:
      repository: github.com/jeetmundra52-web/vehicle-service-system
      branch: main
      workdir: microservices/booking-service
    build:
      command: npm install
    run:
      command: node index.js
    env:
      PORT: 8000
      # MONGO_URI needs to be added in Koyeb Dashboard
    ports:
      - port: 8000
        protocol: http

  # Frontend (Vite)
  - name: frontend
    git:
      repository: github.com/jeetmundra52-web/vehicle-service-system
      branch: main
      workdir: microservices/frontend
    build:
      command: npm install && npm run build
      image: koyeb/node:20
    run:
      command: npm run preview -- --port 8000 --host
    env:
      PORT: 8000
    routes:
      - path: /
        port: 8000
